services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./../scripts/db/init.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_DB=beer
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
  cache:
    image: redis:alpine
    ports:
      - 6379:6379